name: First_repo

on:
  workflow_dispatch:

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting message
        run: echo "Hello World!"

      - name: Print goodbye message
        run: echo "Good Bye!"
